gui:
  nerdFontsVersion: "3"

  # If true, show the number of lines changed per file in the Files view
  showNumstatInFilesView: true
  

notARepository: skip

git:
  # If true, periodically fetch from remote
  autoFetch: false

  diffRenderers:
    - command: delta --dark --paging=never

# Background refreshes
refresher:
  # File/submodule refresh interval in seconds.
  # Auto-refresh can be disabled via option 'git.autoRefresh'.
  refreshInterval: 10

  # Re-fetch interval in seconds.
  # Auto-fetch can be disabled via option 'git.autoFetch'.
  fetchInterval: 60
