tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "buo/cask-upgrade"

brew "mas"
brew "gpg"

brew "asdf"
brew "bat"
brew "broot"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "httpie"
brew "lazydocker"
brew "lazygit"
brew "lsd"
brew "micro"
brew "openssl"
brew "thefuck"
brew "tree"
brew "tmux"

cask "stats"
cask "iterm2"
cask "visual-studio-code"
cask "1password"
cask "1password/tap/1password-cli"
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"
