# Helix themes
[".config/helix/themes/catppuccin_frappe.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/helix/refs/heads/main/themes/default/catppuccin_frappe.toml"
[".config/helix/themes/catppuccin_latte.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/helix/refs/heads/main/themes/default/catppuccin_latte.toml"
[".config/helix/themes/catppuccin_macchiato.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/helix/refs/heads/main/themes/default/catppuccin_macchiato.toml"
[".config/helix/themes/catppuccin_mocha.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/helix/refs/heads/main/themes/default/catppuccin_mocha.toml"
