# Config reference: https://docs.helix-editor.com/configuration.html
theme = "catppuccin_macchiato"

[editor]
line-number = "absolute"
cursorline = true
rulers = [88]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-modification-indicator", "file-name", "separator", "spacer", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# Render whitespace characters
[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
